import Head from "next/head";
import Navbar from "../../components/Navbar";

import CenterSide from "../../components/CenterSide";
import LeftSide from "../../components/LeftSide";
import ScrollToTopButton from "../../components/ScrollToTopButton";


export default function Home() {
  return (
    <>
      <Head>
        <title>Juan Gutierrez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width-device-width, initial-scale-1" />
        <link rel="icon" href="favcon.ico" />
      </Head>
      <main className="w-full h-screen font-montserrat bg-bodyColor text-textLight 
      overflow-x-hidden overflow-y-scroll" >
        <Navbar/>
        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between" >
          <div>
            <LeftSide/>
          </div>
          <div>
            <CenterSide/>
          </div>
          <div>
            <ScrollToTopButton/>
          </div>
        </div>
      </main>
    </>
  );
}
